[pytest]
testpaths=

markers=
     passed_case
     broken_case
     failed_case
     reboot
     run

log_cli = true
log_cli_level = INFO
log_cli_date_format=%Y-%m-%d %H:%M:%S
log_cli_format = %(asctime)-6s: %(levelname)s -> %(module)s -> %(funcName)s -> %(lineno)d -> %(message)s
addopts = --color=yes


